/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../../App`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useAuth`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/transfer`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Input`; params?: Router.UnknownInputParams; } | { pathname: `/../../../web/vitest.config`; params?: Router.UnknownInputParams; } | { pathname: `/../services/auth`; params?: Router.UnknownInputParams; } | { pathname: `/../services/accounts`; params?: Router.UnknownInputParams; } | { pathname: `/../storage/token`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../../App`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Button`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useAuth`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/transfer`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Input`; params?: Router.UnknownOutputParams; } | { pathname: `/../../../web/vitest.config`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/accounts`; params?: Router.UnknownOutputParams; } | { pathname: `/../storage/token`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/explore${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/../../App${`?${string}` | `#${string}` | ''}` | `/../components/Button${`?${string}` | `#${string}` | ''}` | `/../hooks/useAuth${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/transfer${`?${string}` | `#${string}` | ''}` | `/../components/Input${`?${string}` | `#${string}` | ''}` | `/../../../web/vitest.config${`?${string}` | `#${string}` | ''}` | `/../services/auth${`?${string}` | `#${string}` | ''}` | `/../services/accounts${`?${string}` | `#${string}` | ''}` | `/../storage/token${`?${string}` | `#${string}` | ''}` | `/../contexts/AuthContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../../App`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useAuth`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/transfer`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Input`; params?: Router.UnknownInputParams; } | { pathname: `/../../../web/vitest.config`; params?: Router.UnknownInputParams; } | { pathname: `/../services/auth`; params?: Router.UnknownInputParams; } | { pathname: `/../services/accounts`; params?: Router.UnknownInputParams; } | { pathname: `/../storage/token`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
